--------------------------------------------------------
--  File created - Wednesday-March-02-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQ_USER
--------------------------------------------------------

   CREATE SEQUENCE  "C##TAXARE1"."SEQ_USER"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table CHECKPOINT
--------------------------------------------------------

  CREATE TABLE "C##TAXARE1"."CHECKPOINT" 
   (	"ID" NUMBER(*,0), 
	"BALANCE_WAGONS" NUMBER(*,0), 
	"DATA_CHECK" CHAR(12 BYTE), 
	"IS_DELETED" NUMBER(*,0) DEFAULT 0, 
	"TRANSACTION_ID" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table OTF
--------------------------------------------------------

  CREATE TABLE "C##TAXARE1"."OTF" 
   (	"ID" CHAR(6 BYTE), 
	"NAME" VARCHAR2(50 BYTE), 
	"IS_DELETED" NUMBER(*,0) DEFAULT 0, 
	"TRAFIC_TYPE_ID" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ROLES
--------------------------------------------------------

  CREATE TABLE "C##TAXARE1"."ROLES" 
   (	"ID" NUMBER(*,0), 
	"ROLE_NAME" VARCHAR2(20 BYTE), 
	"IS_DELETED" NUMBER(*,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON TABLE "C##TAXARE1"."ROLES"  IS 'Tabela utilizatori';
--------------------------------------------------------
--  DDL for Table STATION
--------------------------------------------------------

  CREATE TABLE "C##TAXARE1"."STATION" 
   (	"ID" CHAR(5 BYTE), 
	"NAME" VARCHAR2(30 BYTE), 
	"IS_DELETED" NUMBER(*,0) DEFAULT 0, 
	"TAXES_VALUES_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TAXES_TYPES
--------------------------------------------------------

  CREATE TABLE "C##TAXARE1"."TAXES_TYPES" 
   (	"ID" NUMBER(*,0), 
	"DESCRIPTION" VARCHAR2(20 BYTE), 
	"IS_DELETED" NUMBER(*,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON TABLE "C##TAXARE1"."TAXES_TYPES"  IS 'Bareme tarifare
';
--------------------------------------------------------
--  DDL for Table TAXES_VALUES
--------------------------------------------------------

  CREATE TABLE "C##TAXARE1"."TAXES_VALUES" 
   (	"ID" NUMBER(*,0), 
	"DATE_TO_START" CHAR(8 BYTE), 
	"CT1_C" FLOAT(6), 
	"CT2_C" FLOAT(6), 
	"CT1_M" FLOAT(6), 
	"CT2_M" FLOAT(6), 
	"IS_DELETED" NUMBER(*,0) DEFAULT 0, 
	"TAXES_TYPES_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TRAFIC_TYPE
--------------------------------------------------------

  CREATE TABLE "C##TAXARE1"."TRAFIC_TYPE" 
   (	"ID" CHAR(1 BYTE), 
	"NAME" VARCHAR2(20 BYTE), 
	"IS_DELETED" NUMBER(*,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TRANSACTION
--------------------------------------------------------

  CREATE TABLE "C##TAXARE1"."TRANSACTION" 
   (	"ID" NUMBER(*,0), 
	"SENS" CHAR(1 BYTE), 
	"DATE_TIME" CHAR(6 BYTE), 
	"TRAIN_NUMBER" VARCHAR2(8 BYTE), 
	"VAGON_NUMBER" NUMBER(*,0), 
	"TIME_STAMP" DATE, 
	"IS_DELETED" NUMBER(*,0) DEFAULT 0, 
	"USER_ID" NUMBER(*,0), 
	"OTF_ID" CHAR(6 BYTE), 
	"STATION_ID" CHAR(5 BYTE), 
	"STATION_ID1" NUMBER(*,0), 
	"STATION_ID11" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "C##TAXARE1"."USERS" 
   (	"ID" NUMBER(*,0), 
	"NICKNAME" VARCHAR2(20 BYTE), 
	"LAST_NAME" VARCHAR2(20 BYTE), 
	"FIRST_NAME" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(36 BYTE), 
	"IS_DELETED" NUMBER(*,0) DEFAULT 0, 
	"ROLES_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##TAXARE1.CHECKPOINT
SET DEFINE OFF;
REM INSERTING into C##TAXARE1.OTF
SET DEFINE OFF;
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000072','PSP Cargo',0,'M');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000071','LTE-RAIL RO',0,'M');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000084','RELOC CALATORI',0,'C');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000082','FOXRAIL',0,'M');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000081','PRVA SLOVENSKA ZEL',0,'M');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000010','G.F.R',0,'M');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000009','SERVTRANS INVEST SA (M)',0,'M');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000008','ROMPETROL LOGISTIC SA',0,'M');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000024','TRANSFEROVIARIA SA',0,'M');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000038','Cerealcom SA',0,'M');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000023','RAIL INTERNATIONAL SA',0,'M');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000013','ROMANIA EUROEST SA',0,'M');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000011','CLASSFER S.R.L.',0,'M');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000012','TRANSFEROVIAR GRUP',0,'M');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000044','SERVTRANS INVEST SA (C)',0,'C');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000020','CRIMBO GAS GIURGIU SRL',0,'M');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000025','33 ICIM Arad',0,'M');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000014','CARGO TRANS VAGON',0,'M');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000032','VIATERRA SPEDITION',0,'M');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000027','RC - CF TRANS SRL',0,'M');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000041','Societatea Feroviara de Turism',0,'C');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000017','SOFTRANS MF',0,'M');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000031','TEF SRL',0,'M');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000019','DB CARGO ROMANIA',0,'M');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000029','KAIROS SRL',0,'M');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000039','REGIOTRANS BV',0,'C');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000033','TRANSBLUE',0,'M');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000040','Regional SRL',0,'C');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000037','SERVICE CF REC  SA',0,'M');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000036','TRANS CONFER CRAIOVA SA',0,'M');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000047','Dori Trans SRL (C)',0,'C');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000046','T.F.C',0,'C');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000002','UNICOM TRANZIT',0,'M');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000064','R.T.S.',0,'M');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000042','Rail Cargo Austria',0,'M');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000058','Carmensimi Grup SRL',0,'M');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000043','Dori Trans SRL (M)',0,'M');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000045','Grup Transport Feroviar SA',0,'M');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000048','RAIL FORCE',0,'M');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000049','FEROTRANS TFI SRL (M)',0,'M');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000050','FEROTRANS TFI SRL (C)',0,'C');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000051','C.F.M.',0,'C');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000052','MAV-START',0,'C');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000053','SERBIAN RAILWAYS',0,'C');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000054','VEST TRANS RAIL MF',0,'M');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000055','RAIL CARGO ROMANIA',0,'M');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000056','PORR RAILWAY TRANSPORT SRL',0,'M');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000059','VTR CALATORI',0,'C');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000063','TRANS RAIL',0,'M');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000060','Electro Comp SRL (M)',0,'M');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000061','CER-FERSPED',0,'M');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000062','TEHNOTRANS',0,'M');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000066','COLAS RAIL',0,'M');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000065','IRT Timisoara',0,'M');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000067','EC T.F.',0,'M');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000069','SOFTRANS CALATORI',0,'C');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000068','INTERREGIONAL',0,'C');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000070','TIM RAIL CARGO',0,'M');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000073','LOGISTICA FEROVIARA',0,'M');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000074','EXPRESS FWD',0,'M');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000075','ASTRA TRANS CARPATIC',0,'C');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000076','I.R.T. CCF',0,'M');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000077','REGIO CALATORI',0,'C');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000078','MIRO CARGO',0,'M');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000080','GP RAIL CARGO',0,'M');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000085','TRUSTUL FEROVIAR CARPATI',0,'M');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000083','RELOC MARFA',0,'M');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000086','UNITED RAILWAYS',0,'M');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000087','T.HUNGARY Craiova',0,'M');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000088','RAIL OPERATIONS',0,'M');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000028','CONSTANTIN GRUP',0,'M');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000079','ROFERSPED',0,'M');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000030','CTF BUCURESTI SA',0,'M');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000CFR','CNCF CFR SA',0,'M');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000000','SNTFM CFR MARFA',0,'M');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000C_1','SNTFC CFR CALATORI',0,'C');
Insert into C##TAXARE1.OTF (ID,NAME,IS_DELETED,TRAFIC_TYPE_ID) values ('000021','TRANSCOMBI SA',0,'M');
REM INSERTING into C##TAXARE1.ROLES
SET DEFINE OFF;
Insert into C##TAXARE1.ROLES (ID,ROLE_NAME,IS_DELETED) values (99,'Administrator',0);
Insert into C##TAXARE1.ROLES (ID,ROLE_NAME,IS_DELETED) values (50,'Utilizator',0);
Insert into C##TAXARE1.ROLES (ID,ROLE_NAME,IS_DELETED) values (10,'Vizitator',0);
REM INSERTING into C##TAXARE1.STATION
SET DEFINE OFF;
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('10017',' Bucuresti Nord Gr.A',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('10043',' Bucuresti Basarab',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('10146',' Chiajna',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('10287',' Videle',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('10445',' Rosiori Nord',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('10574',' Caracal',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('10732',' Banu Maracine HM',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('10770',' Craiova',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('10809',' Cernele',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('10823',' Isalnita',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('10902',' Filiasi',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('10938',' Turceni',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('11085',' Balota',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('11138',' Drobeta Tr. Severin Marfuri',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('11140',' Drobeta Tr.Severin',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('11231',' Orsova',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('11401',' Poarta HM',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('11554',' Caransebes',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('11695',' Lugoj',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('11877',' Timisoara Est',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('11906',' Timisoara Nord',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('12039',' Jimbolia',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('12144',' Bucuresti Vest',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('12431',' Titu',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('12596',' Golesti',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('12613',' Pitesti',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('12651',' Bradu Rafinarie HM',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('12895',' Slatina',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('12948',' Piatra Olt',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('13198',' Targoviste',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('13306',' Fieni',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('13332',' Pietrosita HM',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('13382',' Ciumesti',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('13538',' Argesel HM',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('13863',' Bucuresti Progresu',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('14037',' Giurgiu Nord',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('14049',' Giurgiu HM',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('14178',' Radulesti HM',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('14283',' Stanesti HM',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('14312',' Rosiori HM',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('14518',' Alexandria',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('15419',' Motru Est',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('15536',' Caransebes Triaj',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('15938',' Timisoara C.E.T.',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('16205',' Resita Nord',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('16281',' Resita Sud HM',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('16310',' Semenic HM',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('16645',' Stamora Moravita',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('17211',' Cruceni hcv.',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('17417',' Bucuresti Nord Gr.B',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('17431',' PM Giulesti',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('18033',' Plopsoru',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('18186',' Dragotesti HM',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('20232',' Fagaras',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('20658',' Sibiu',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('21016',' R1 Vintu',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('21028',' Vintu de Jos',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('21030',' R2 Vintu',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('21236',' Simeria',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('21286',' Deva',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('21315',' Mintia',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('21705',' Radna',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('21808',' Glogovat',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('21834',' Arad',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('21925',' Curtici',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('22096',' Zarnesti',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('22357',' Babeni',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('22371',' Govora',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('22400',' Raureni',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('22436',' Ramnicu Valcea',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('22929',' Coslariu',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('23428',' Targu Jiu',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('23624',' Petrosani',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('23739',' Banita',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('23832',' Pui',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('23894',' Subcetate',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('24020',' Calan Bai',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('24082',' Simeria Triaj',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('24496',' Vulcan HM',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('24616',' Rovinari HM',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('24666',' Barsesti HM',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('24812',' Pestis',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('25177',' Remetea Mica',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('25268',' Ronat Triaj',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('25426',' Aradu Nou',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('25440',' Arad Vest',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('25567',' Nadlac',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('26004',' Nerau hcv.',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('26145',' Lovrin',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('26195',' Sannicolau Mare',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('27101',' Zlatna hcv.',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('27539',' Berbesti',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('27541',' Alunu HM',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('30110',' Chitila',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('30146',' Buftea',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('30225',' Brazi',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('30251',' Ploiesti Triaj',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('30342',' Ploiesti Crang HM',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('30421',' Campina',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('30615',' Predeal',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('30691',' Brasov',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('30756',' Brasov Triaj',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('30835',' Stupini HM',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('31011',' Racos HM',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('31047',' Rupea',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('31102',' Beia HM',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('31217',' Sighisoara',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('31334',' Medias',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('31530',' Blaj',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('31645',' Teius',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('31774',' Razboieni',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('31798',' Calarasi Turda HM',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('31827',' Campia Turzii',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('31920',' Cojocna HM',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('31982',' Cluj Napoca Est',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('32015',' Cluj Napoca',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('32261',' Huedin',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('32508',' Alesd',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('32558',' Tileagd',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('32637',' Oradea Est',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('32663',' Oradea',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('32742',' Episcopia Bihor',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('32883',' Crangu Lui Bot HM',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('32948',' I. L. Caragiale',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('33368',' Slanic',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('33605',' Odorhei',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('34609',' Holod',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('34790',' Vascau HM',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('35110',' Utvinisu Nou',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('35407',' Salonta',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('35627',' SEMNAL Ineu',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('35639',' Ineu',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('35653',' Ram. Ineu',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('36126',' Brad',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('36322',' Cermei hcv.',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('40139',' Sfantu Gheorghe',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('40373',' Miercurea Ciuc',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('40402',' Siculeni',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('40531',' Voslabeni HM',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('40830',' Deda',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('41054',' Beclean pe Somes',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('41145',' Dej',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('41195',' Dej Calatori',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('41444',' Jibou',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('41638',' Baia Mare',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('42058',' Intorsura Buzaului HM',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('42137',' Moacsa HM',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('42333',' Bretcu HM',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('42606',' Targu Mures',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('42644',' Targu Mures Sud',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('42814',' Ludus',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('42967',' Bistrita Nord',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('43052',' Bistrita Bargaului hcv.',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('43246',' Sarmasel hcv.',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('43820',' Sighetu Marmatiei',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('44240',' Zalau Nord',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('44329',' Sarmasag',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('44628',' Suplacu de Barcau',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('44707',' Marghita',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('45153',' Valea lui Mihai',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('45323',' Carei',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('45452',' Satu Mare',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('45505',' Porumbesti HM',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('45531',' Halmeu',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('50017',' Ploiesti Sud',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('50079',' Ploiesti Est',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('50342',' Buzau',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('50603',' Focsani',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('50691',' Marasesti',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('50811',' Adjud',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('51059',' Bacau',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('51190',' Roman',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('51346',' Pascani Triaj PO',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('51358',' Pascani',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('51607',' Suceava',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('51645',' Suceava Nord HM',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('51671',' Darmanesti',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('51750',' Dornesti',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('51798',' Vicsani',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('51932',' Ploiesti Nord',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('52156',' Maneciu HM',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('52168',' Gheaba 2 PO',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('52546',' Nehoiasu',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('53174',' Comanesti',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('53394',' Livezi Ciuc',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('53526',' Moinesti HM',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('53813',' Piatra Neamt',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('53916',' Bicaz',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('54233',' Botosani',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('54374',' Dorohoi',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('54661',' Campulung Moldovenesc',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('54702',' Pojorata HM',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('54788',' Argestru HM',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('54817',' Vatra Dornei',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('55110',' Ilva Mica',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('55287',' Cacica HM',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('56152',' Targu Neamt',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('60309',' Tecuci',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('60490',' Barlad',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('60658',' Vaslui',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('60921',' Iasi',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('61016',' Socola',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('61080',' Cristesti Jijia',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('61092',' Ungheni Prut HM',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('61420',' Independenta HM',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('62840',' Targu Frumos',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('63105',' Harlau',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('70031',' Mogosoaia',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('70055',' Balotesti HM',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('70237',' Urziceni',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('70512',' Faurei',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('70706',' Braila',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('70835',' Barbosi',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('70859',' Barbosi Port HM',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('70938',' Malina',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('70976',' Catusa',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('71059',' Galati',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('71102',' Galati Brates',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('71164',' Galati Larga',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('71463',' Ghighiu',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('72120',' Buzau Sud',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('72637',' Ramificatia C.S.G.',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('72936',' Barbosi Triaj Gr. A',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('80036',' Bucuresti Baneasa',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('80074',' Bucuresti Obor',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('80103',' Pantelimon',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('80256',' Lehliu',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('80361',' Ciulnita',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('80505',' Fetesti',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('80610',' Saligny',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('80684',' Medgidia',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('80701',' Romcim Medgidia',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('80749',' Dorobantu',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('80830',' Palas',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('80892',' Constanta',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('80983',' Constanta Port Zona B',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('80995',' Constanta Port Mol 5',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('81016',' Agigea Nord',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('81030',' Constanta Terminal Ferry Boat',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('81054',' Agigea Ecluza HM',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('81183',' Mangalia',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('81315',' Bucuresti Grivita',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('81664',' Titan Sud HM',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('81705',' Bucuresti Sud',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('81846',' Oltenita',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('82072',' Slobozia Veche',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('82175',' Calarasi Nord HM',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('82204',' Calarasi Sud',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('83193',' Tulcea Marfuri',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('83430',' Capul Midia',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('83480',' P2 Capul Midia',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('83650',' Constanta Marfuri',0,0);
Insert into C##TAXARE1.STATION (ID,NAME,IS_DELETED,TAXES_VALUES_ID) values ('89898',' Agigea Nord Oil Terminal',0,0);
REM INSERTING into C##TAXARE1.TAXES_TYPES
SET DEFINE OFF;
Insert into C##TAXARE1.TAXES_TYPES (ID,DESCRIPTION,IS_DELETED) values (1,'Barem Unu',0);
Insert into C##TAXARE1.TAXES_TYPES (ID,DESCRIPTION,IS_DELETED) values (2,'Barem Doi',0);
Insert into C##TAXARE1.TAXES_TYPES (ID,DESCRIPTION,IS_DELETED) values (3,'Barem Preferential',0);
REM INSERTING into C##TAXARE1.TAXES_VALUES
SET DEFINE OFF;
Insert into C##TAXARE1.TAXES_VALUES (ID,DATE_TO_START,CT1_C,CT2_C,CT1_M,CT2_M,IS_DELETED,TAXES_TYPES_ID) values (1,'20200101',0,2,0,3.5,0,1);
Insert into C##TAXARE1.TAXES_VALUES (ID,DATE_TO_START,CT1_C,CT2_C,CT1_M,CT2_M,IS_DELETED,TAXES_TYPES_ID) values (3,'20200801',0,3,0,5,0,1);
Insert into C##TAXARE1.TAXES_VALUES (ID,DATE_TO_START,CT1_C,CT2_C,CT1_M,CT2_M,IS_DELETED,TAXES_TYPES_ID) values (2,'20200101',1,2.5,1,4.5,0,2);
Insert into C##TAXARE1.TAXES_VALUES (ID,DATE_TO_START,CT1_C,CT2_C,CT1_M,CT2_M,IS_DELETED,TAXES_TYPES_ID) values (4,'20200801',0,4,0,6,0,2);
Insert into C##TAXARE1.TAXES_VALUES (ID,DATE_TO_START,CT1_C,CT2_C,CT1_M,CT2_M,IS_DELETED,TAXES_TYPES_ID) values (5,'20200101',0,1,0,1,0,3);
REM INSERTING into C##TAXARE1.TRAFIC_TYPE
SET DEFINE OFF;
Insert into C##TAXARE1.TRAFIC_TYPE (ID,NAME,IS_DELETED) values ('C','Trafic calatori',0);
Insert into C##TAXARE1.TRAFIC_TYPE (ID,NAME,IS_DELETED) values ('M','Trafic marfa',0);
REM INSERTING into C##TAXARE1.TRANSACTION
SET DEFINE OFF;
REM INSERTING into C##TAXARE1.USERS
SET DEFINE OFF;
Insert into C##TAXARE1.USERS (ID,NICKNAME,LAST_NAME,FIRST_NAME,PASSWORD,IS_DELETED,ROLES_ID) values (2,'MG','Grigore','Marcel','E10ADC3949BA59ABBE56E057F20F883E',0,0);
Insert into C##TAXARE1.USERS (ID,NICKNAME,LAST_NAME,FIRST_NAME,PASSWORD,IS_DELETED,ROLES_ID) values (1,'Iulian','Bogdanovici','Iulian-Bogdan','E10ADC3949BA59ABBE56E057F20F883E',0,99);
--------------------------------------------------------
--  DDL for Index CHECKPOINT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##TAXARE1"."CHECKPOINT_PK" ON "C##TAXARE1"."CHECKPOINT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index OTF_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##TAXARE1"."OTF_PK" ON "C##TAXARE1"."OTF" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ROLES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##TAXARE1"."ROLES_PK" ON "C##TAXARE1"."ROLES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index STATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##TAXARE1"."STATION_PK" ON "C##TAXARE1"."STATION" ("ID", "TAXES_VALUES_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TAXES_TYPES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##TAXARE1"."TAXES_TYPES_PK" ON "C##TAXARE1"."TAXES_TYPES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TAXES_VALUES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##TAXARE1"."TAXES_VALUES_PK" ON "C##TAXARE1"."TAXES_VALUES" ("ID", "TAXES_TYPES_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TRAFIC_TYPE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##TAXARE1"."TRAFIC_TYPE_PK" ON "C##TAXARE1"."TRAFIC_TYPE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TRANSACTION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##TAXARE1"."TRANSACTION_PK" ON "C##TAXARE1"."TRANSACTION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##TAXARE1"."USER_PK" ON "C##TAXARE1"."USERS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CHECKPOINT
--------------------------------------------------------

  ALTER TABLE "C##TAXARE1"."CHECKPOINT" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##TAXARE1"."CHECKPOINT" MODIFY ("BALANCE_WAGONS" NOT NULL ENABLE);
  ALTER TABLE "C##TAXARE1"."CHECKPOINT" MODIFY ("IS_DELETED" NOT NULL ENABLE);
  ALTER TABLE "C##TAXARE1"."CHECKPOINT" MODIFY ("TRANSACTION_ID" NOT NULL ENABLE);
  ALTER TABLE "C##TAXARE1"."CHECKPOINT" ADD CONSTRAINT "CHECKPOINT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table OTF
--------------------------------------------------------

  ALTER TABLE "C##TAXARE1"."OTF" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##TAXARE1"."OTF" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "C##TAXARE1"."OTF" MODIFY ("IS_DELETED" NOT NULL ENABLE);
  ALTER TABLE "C##TAXARE1"."OTF" MODIFY ("TRAFIC_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "C##TAXARE1"."OTF" ADD CONSTRAINT "OTF_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TAXES_VALUES
--------------------------------------------------------

  ALTER TABLE "C##TAXARE1"."TAXES_VALUES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##TAXARE1"."TAXES_VALUES" MODIFY ("DATE_TO_START" NOT NULL ENABLE);
  ALTER TABLE "C##TAXARE1"."TAXES_VALUES" MODIFY ("CT1_C" NOT NULL ENABLE);
  ALTER TABLE "C##TAXARE1"."TAXES_VALUES" MODIFY ("CT2_C" NOT NULL ENABLE);
  ALTER TABLE "C##TAXARE1"."TAXES_VALUES" MODIFY ("CT1_M" NOT NULL ENABLE);
  ALTER TABLE "C##TAXARE1"."TAXES_VALUES" MODIFY ("CT2_M" NOT NULL ENABLE);
  ALTER TABLE "C##TAXARE1"."TAXES_VALUES" MODIFY ("IS_DELETED" NOT NULL ENABLE);
  ALTER TABLE "C##TAXARE1"."TAXES_VALUES" MODIFY ("TAXES_TYPES_ID" NOT NULL ENABLE);
  ALTER TABLE "C##TAXARE1"."TAXES_VALUES" ADD CONSTRAINT "TAXES_VALUES_PK" PRIMARY KEY ("ID", "TAXES_TYPES_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TRANSACTION
--------------------------------------------------------

  ALTER TABLE "C##TAXARE1"."TRANSACTION" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##TAXARE1"."TRANSACTION" MODIFY ("SENS" NOT NULL ENABLE);
  ALTER TABLE "C##TAXARE1"."TRANSACTION" MODIFY ("TRAIN_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "C##TAXARE1"."TRANSACTION" MODIFY ("VAGON_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "C##TAXARE1"."TRANSACTION" MODIFY ("TIME_STAMP" NOT NULL ENABLE);
  ALTER TABLE "C##TAXARE1"."TRANSACTION" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "C##TAXARE1"."TRANSACTION" MODIFY ("OTF_ID" NOT NULL ENABLE);
  ALTER TABLE "C##TAXARE1"."TRANSACTION" MODIFY ("STATION_ID" NOT NULL ENABLE);
  ALTER TABLE "C##TAXARE1"."TRANSACTION" MODIFY ("STATION_ID1" NOT NULL ENABLE);
  ALTER TABLE "C##TAXARE1"."TRANSACTION" MODIFY ("STATION_ID11" NOT NULL ENABLE);
  ALTER TABLE "C##TAXARE1"."TRANSACTION" ADD CONSTRAINT "TRANSACTION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ROLES
--------------------------------------------------------

  ALTER TABLE "C##TAXARE1"."ROLES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##TAXARE1"."ROLES" MODIFY ("ROLE_NAME" NOT NULL ENABLE);
  ALTER TABLE "C##TAXARE1"."ROLES" MODIFY ("IS_DELETED" NOT NULL ENABLE);
  ALTER TABLE "C##TAXARE1"."ROLES" ADD CONSTRAINT "ROLES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STATION
--------------------------------------------------------

  ALTER TABLE "C##TAXARE1"."STATION" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##TAXARE1"."STATION" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "C##TAXARE1"."STATION" MODIFY ("TAXES_VALUES_ID" NOT NULL ENABLE);
  ALTER TABLE "C##TAXARE1"."STATION" ADD CONSTRAINT "STATION_PK" PRIMARY KEY ("ID", "TAXES_VALUES_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TAXES_TYPES
--------------------------------------------------------

  ALTER TABLE "C##TAXARE1"."TAXES_TYPES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##TAXARE1"."TAXES_TYPES" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "C##TAXARE1"."TAXES_TYPES" MODIFY ("IS_DELETED" NOT NULL ENABLE);
  ALTER TABLE "C##TAXARE1"."TAXES_TYPES" ADD CONSTRAINT "TAXES_TYPES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TRAFIC_TYPE
--------------------------------------------------------

  ALTER TABLE "C##TAXARE1"."TRAFIC_TYPE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##TAXARE1"."TRAFIC_TYPE" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "C##TAXARE1"."TRAFIC_TYPE" ADD CONSTRAINT "TRAFIC_TYPE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "C##TAXARE1"."USERS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##TAXARE1"."USERS" MODIFY ("NICKNAME" NOT NULL ENABLE);
  ALTER TABLE "C##TAXARE1"."USERS" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "C##TAXARE1"."USERS" MODIFY ("FIRST_NAME" NOT NULL ENABLE);
  ALTER TABLE "C##TAXARE1"."USERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "C##TAXARE1"."USERS" MODIFY ("IS_DELETED" NOT NULL ENABLE);
  ALTER TABLE "C##TAXARE1"."USERS" MODIFY ("ROLES_ID" NOT NULL ENABLE);
  ALTER TABLE "C##TAXARE1"."USERS" ADD CONSTRAINT "USER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
