-- Generated by Oracle SQL Developer Data Modeler 21.4.1.349.1605
--   at:        2022-02-02 15:49:49 EET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE checkpoint (
    id             INTEGER NOT NULL,
    balance_wagons INTEGER NOT NULL,
    is_deleted     INTEGER DEFAULT 0 NOT NULL,
    otf_id         CHAR(6) NOT NULL,
    station_id     CHAR(5) NOT NULL,
    transaction_id INTEGER NOT NULL,
    data_check     CHAR(12)
);

ALTER TABLE checkpoint ADD CONSTRAINT checkpoint_pk PRIMARY KEY ( id );

CREATE TABLE otf (
    id             CHAR(6) NOT NULL,
    name           VARCHAR2(20) NOT NULL,
    is_deleted     INTEGER DEFAULT 0 NOT NULL,
    trafic_type_id CHAR(1) NOT NULL
);

ALTER TABLE otf ADD CONSTRAINT otf_pk PRIMARY KEY ( id );

CREATE TABLE relation_23 (
    taxes_types_id INTEGER NOT NULL,
    station_id     CHAR(5) NOT NULL
);

ALTER TABLE relation_23 ADD CONSTRAINT relation_23_pk PRIMARY KEY ( taxes_types_id,
                                                                    station_id );

CREATE TABLE relation_25 (
    transaction_id INTEGER NOT NULL,
    taxes_types_id INTEGER NOT NULL
);

ALTER TABLE relation_25 ADD CONSTRAINT relation_25_pk PRIMARY KEY ( transaction_id,
                                                                    taxes_types_id );

CREATE TABLE roles (
    id         INTEGER NOT NULL,
    role_name  VARCHAR2(20) NOT NULL,
    is_deleted INTEGER DEFAULT 0 NOT NULL
);

COMMENT ON TABLE roles IS
    'Tabela utilizatori';

ALTER TABLE roles ADD CONSTRAINT roles_pk PRIMARY KEY ( id );

CREATE TABLE station (
    id         CHAR(5) NOT NULL,
    name       VARCHAR2(30) NOT NULL,
    is_deleted INTEGER DEFAULT 0
);

ALTER TABLE station ADD CONSTRAINT station_pk PRIMARY KEY ( id );

CREATE TABLE taxes_types (
    id             INTEGER NOT NULL,
    description    VARCHAR2(20) NOT NULL,
    is_deleted     INTEGER DEFAULT 0 NOT NULL,
    trafic_type_id CHAR(1) NOT NULL
);

ALTER TABLE taxes_types ADD CONSTRAINT taxes_types_pk PRIMARY KEY ( id );

CREATE TABLE taxes_values (
    id             INTEGER NOT NULL,
    date_to_start  CHAR(8) NOT NULL,
    ct1            FLOAT(6) NOT NULL,
    ct2            FLOAT(6) NOT NULL,
    is_deleted     INTEGER DEFAULT 0 NOT NULL,
    taxes_types_id INTEGER NOT NULL,
    trafic_type_id CHAR(1) NOT NULL
);

ALTER TABLE taxes_values ADD CONSTRAINT taxes_values_pk PRIMARY KEY ( id );

CREATE TABLE trafic_type (
    id         CHAR(1) NOT NULL,
    name       VARCHAR2(20) NOT NULL,
    is_deleted INTEGER DEFAULT 0
);

ALTER TABLE trafic_type ADD CONSTRAINT trafic_type_pk PRIMARY KEY ( id );

CREATE TABLE transaction (
    id           INTEGER NOT NULL,
    sens         CHAR(1) NOT NULL,
    date_time    CHAR(6),
    train_number VARCHAR2(8) NOT NULL,
    vagon_number INTEGER NOT NULL,
    time_stamp   DATE NOT NULL,
    is_deleted   INTEGER DEFAULT 0,
    user_id      INTEGER NOT NULL,
    otf_id       CHAR(6) NOT NULL,
    station_id   CHAR(5) NOT NULL
);

ALTER TABLE transaction ADD CONSTRAINT transaction_pk PRIMARY KEY ( id );

CREATE TABLE "User" (
    id         INTEGER NOT NULL,
    nickname   VARCHAR2(20) NOT NULL,
    last_name  VARCHAR2(20) NOT NULL,
    first_name VARCHAR2(20) NOT NULL,
    password   VARCHAR2(36) NOT NULL,
    is_deleted INTEGER DEFAULT 0 NOT NULL,
    roles_id   INTEGER NOT NULL
);

ALTER TABLE "User" ADD CONSTRAINT user_pk PRIMARY KEY ( id );

ALTER TABLE checkpoint
    ADD CONSTRAINT checkpoint_otf_fk FOREIGN KEY ( otf_id )
        REFERENCES otf ( id );

ALTER TABLE checkpoint
    ADD CONSTRAINT checkpoint_station_fk FOREIGN KEY ( station_id )
        REFERENCES station ( id );

ALTER TABLE checkpoint
    ADD CONSTRAINT checkpoint_transaction_fk FOREIGN KEY ( transaction_id )
        REFERENCES transaction ( id );

ALTER TABLE otf
    ADD CONSTRAINT otf_trafic_fk FOREIGN KEY ( trafic_type_id )
        REFERENCES trafic_type ( id );

ALTER TABLE relation_23
    ADD CONSTRAINT relation_23_station_fk FOREIGN KEY ( station_id )
        REFERENCES station ( id );

ALTER TABLE relation_23
    ADD CONSTRAINT relation_23_tx_typ_fk FOREIGN KEY ( taxes_types_id )
        REFERENCES taxes_types ( id );

ALTER TABLE relation_25
    ADD CONSTRAINT relation_25_transaction_fk FOREIGN KEY ( transaction_id )
        REFERENCES transaction ( id );

ALTER TABLE relation_25
    ADD CONSTRAINT relation_25_tx_typ_fk FOREIGN KEY ( taxes_types_id )
        REFERENCES taxes_types ( id );

ALTER TABLE transaction
    ADD CONSTRAINT transaction_otf_fk FOREIGN KEY ( otf_id )
        REFERENCES otf ( id );

ALTER TABLE transaction
    ADD CONSTRAINT transaction_station_fk FOREIGN KEY ( station_id )
        REFERENCES station ( id );

ALTER TABLE transaction
    ADD CONSTRAINT transaction_user_fk FOREIGN KEY ( user_id )
        REFERENCES "User" ( id );

ALTER TABLE taxes_types
    ADD CONSTRAINT tx_typ_trafic_fk FOREIGN KEY ( trafic_type_id )
        REFERENCES trafic_type ( id );

ALTER TABLE taxes_values
    ADD CONSTRAINT tx_val_trafic_fk FOREIGN KEY ( trafic_type_id )
        REFERENCES trafic_type ( id );

ALTER TABLE taxes_values
    ADD CONSTRAINT tx_val_tx_typ_fk FOREIGN KEY ( taxes_types_id )
        REFERENCES taxes_types ( id );

ALTER TABLE "User"
    ADD CONSTRAINT user_roles_fk FOREIGN KEY ( roles_id )
        REFERENCES roles ( id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            11
-- CREATE INDEX                             0
-- ALTER TABLE                             26
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
